### PR TITLE
Add newer rubies to travis

### PR DESCRIPTION
**Pull request by jrafanie**

### CODE REVIEW

**Comment by duerst** [comment]
For newer versions, `String#unicode_normalize`,... are used, so things should work anyway.

**Comment by jrafanie** [comment]
Thanks @duerst!  Are you suggesting we close this PR?  My intention was to add new rubies to avoid future regressions.

**Comment by chrisarcand** [comment]
Bump?

**Comment by duerst** [comment]
@crisarcand: Are you bumping me or @knu or somebody else?
@jrafanie: I'm fine either way. But each Ruby version uses a different Unicode version, so that may make things a bit more complicated (see https://www.sw.it.aoyama.ac.jp/2017/pub/Ruby_Kaigi/#UnicodeVersions).

**Comment by chrisarcand** [comment]
@duerst Just the issue in general for any maintainer, be it you or or knu or someone else; as @jrafanie asked, wondering if this PR should just be closed (as it looks like there's no purpose to using this gem with Ruby 2.2+?) or merged. 🙇

**Comment by jrafanie** [comment]
@duerst Are you saying that this gem is not needed for newer rubies or that we don't have adequate tests for the differences in the unicode versions supported by the various ruby versions?

The reason I opened this PR was because this gem has this in the gemspec:
`gem.required_ruby_version = '>= 1.9.3'`

and yet, travis isn't testing 2.3 or 2.4 version.  It's unclear if this is an oversight or on purpose.

I'm fine either way, I would just like clarity on this gem's usage on ruby 2.3 and 2.4.

**Comment by knu** [comment]
Thanks!

**Comment by knu** [comment]
I don't like it when Travis CI has not been doing a very good job of maintaining their list of rubies up-to-date and manageable.  I just want to say `- 2.3` and `- 2.4` but they just fail. ☹️

**Comment by knu** [comment]
And the random errors like this: https://travis-ci.org/knu/ruby-unf/jobs/286342949
Even `- jruby` fails occasionally... 😫

**Comment by chrisarcand** [comment]
> I just want to say - 2.3 and - 2.4 but they just fail.

😕 Confused here; you should be able to do exactly that: https://docs.travis-ci.com/user/languages/ruby/   "As we upgrade both RVM and Rubies, aliases like 2.2 or jruby point to different exact versions and patch levels." This is still limited by them keeping it up to date as you mentioned, of course, but I feel like that hasn't been much of an issue.

JRuby... 😬 Unfortunately, a few weeks ago their S3 bucket with Ruby downloads apparently disappeared and I think there are checksum mismatches now with services drawing them such as Travis. See https://github.com/jruby/jruby/issues/4789

**Comment by knu** [comment]
Yeah, I know I should be, but my expectation has been betrayed so many times.  `- 2.3` didn't work even after 2.3.2 was released and that's the lesson I learned.

And thanks for the information about JRuby, `- jruby` not working for about a month seems to be enough of a reason to avoid bothering with it.  I'd just work it around and forget. 😝

**Comment by knu** [comment]
FYI, `- 2.3` and `- 2.4` seem to be working at the moment.  I'm afraid it'd break occasionally with no good reason, though.

In recent memory I recall `- 2.4` kept pointing at 2.4.0 for awhile when `- 2.4.2` was already listed on http://rubies.travis-ci.org/.  Perhaps the build picked the outdated container/instance or something, but that once again firmed my bad impression...

**Pull request merged**
